/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import model.PersonHistory;
import model.UserHistory;

/**
 *
 * @author advai
 */
public class AdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminJPanel
     */
    PersonHistory history;
    UserHistory history1;

    public AdminJPanel(PersonHistory personHistory, UserHistory userHistory) {
        initComponents();
        this.history = personHistory;
        this.history1 = userHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xyz = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        CreatePersonBtn = new javax.swing.JButton();
        PersonListBtn = new javax.swing.JButton();
        SearchPersonBtn = new javax.swing.JButton();
        CreateUserBtn = new javax.swing.JButton();
        ManageUserBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        CreatePersonBtn.setText("CreatePerson:");
        CreatePersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePersonBtnActionPerformed(evt);
            }
        });

        PersonListBtn.setText("PersonList:");
        PersonListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonListBtnActionPerformed(evt);
            }
        });

        SearchPersonBtn.setText("SearchPerson:");
        SearchPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPersonBtnActionPerformed(evt);
            }
        });

        CreateUserBtn.setText("Createuser:");
        CreateUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateUserBtnActionPerformed(evt);
            }
        });

        ManageUserBtn.setText("ManageUser:");
        ManageUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageUserBtnActionPerformed(evt);
            }
        });

        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SearchPersonBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PersonListBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreatePersonBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateUserBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ManageUserBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoutBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(CreatePersonBtn)
                .addGap(35, 35, 35)
                .addComponent(PersonListBtn)
                .addGap(39, 39, 39)
                .addComponent(SearchPersonBtn)
                .addGap(47, 47, 47)
                .addComponent(CreateUserBtn)
                .addGap(39, 39, 39)
                .addComponent(ManageUserBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(LogoutBtn)
                .addGap(50, 50, 50))
        );

        xyz.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        xyz.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xyz)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xyz)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreatePersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePersonBtnActionPerformed
        // TODO add your handling code here:
        CreatePersonJPanel createPanel = new CreatePersonJPanel(history);
        xyz.setRightComponent(createPanel);
        
    }//GEN-LAST:event_CreatePersonBtnActionPerformed

    private void PersonListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonListBtnActionPerformed
        // TODO add your handling code here:
        ListJPanel listPanel = new ListJPanel(history);
        xyz.setRightComponent(listPanel);
    }//GEN-LAST:event_PersonListBtnActionPerformed

    private void SearchPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPersonBtnActionPerformed
        // TODO add your handling code here:
        
        SearchJPanel searchPanel = new SearchJPanel(history);
        xyz.setRightComponent(searchPanel);
    }//GEN-LAST:event_SearchPersonBtnActionPerformed

    private void CreateUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateUserBtnActionPerformed
        // TODO add your handling code here:
        
        CreateUserJPanel createPanel = new CreateUserJPanel(this.history1,this.history);
        xyz.setRightComponent(createPanel);
    }//GEN-LAST:event_CreateUserBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:
        LoginJPanel loginPanel = new LoginJPanel(this.history,this.history1);
        LeftJPanel leftPanel = new LeftJPanel();
        xyz.setRightComponent(loginPanel);
        xyz.setLeftComponent(leftPanel);
        /*LoginJPanel loginPanel = new LoginJPanel();
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.removeAll();
        jPanel1.add(loginPanel);
        jPanel1.revalidate();*/
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void ManageUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageUserBtnActionPerformed
        // TODO add your handling code here:
        
        ManageJPanel managePanel = new ManageJPanel(this.history1);
        xyz.setRightComponent(managePanel);
    }//GEN-LAST:event_ManageUserBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreatePersonBtn;
    private javax.swing.JButton CreateUserBtn;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton ManageUserBtn;
    private javax.swing.JButton PersonListBtn;
    private javax.swing.JButton SearchPersonBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane xyz;
    // End of variables declaration//GEN-END:variables
}
