/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.Person;
import model.PersonHistory;
import model.User;
import model.UserHistory;

/**
 *
 * @author advai
 */
public class CreateUserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateUserJPanel
     */
    PersonHistory history;
    UserHistory history1;
    public CreateUserJPanel(UserHistory history1,PersonHistory history) {
        initComponents();
        this.history1 = history1;
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NUIDlbl = new javax.swing.JLabel();
        UserIdlbl = new javax.swing.JLabel();
        Passwordlbl = new javax.swing.JLabel();
        Statuslbl = new javax.swing.JLabel();
        NUIDtf = new javax.swing.JTextField();
        UserIdtf = new javax.swing.JTextField();
        Enablebtn = new javax.swing.JButton();
        Passwordpf = new javax.swing.JPasswordField();
        Rolelbl = new javax.swing.JLabel();
        Roletf = new javax.swing.JTextField();

        NUIDlbl.setText("NUID:");

        UserIdlbl.setText("UserId:");

        Passwordlbl.setText("Password:");

        Statuslbl.setText("Status:");

        NUIDtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUIDtfActionPerformed(evt);
            }
        });

        Enablebtn.setText("Enable");
        Enablebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnablebtnActionPerformed(evt);
            }
        });

        Rolelbl.setText("Role:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Passwordlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NUIDlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UserIdlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Statuslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Rolelbl))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NUIDtf)
                    .addComponent(UserIdtf)
                    .addComponent(Enablebtn)
                    .addComponent(Passwordpf)
                    .addComponent(Roletf, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUIDlbl)
                    .addComponent(NUIDtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserIdlbl)
                    .addComponent(UserIdtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Rolelbl)
                    .addComponent(Roletf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Passwordlbl)
                    .addComponent(Passwordpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Statuslbl)
                    .addComponent(Enablebtn))
                .addContainerGap(254, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NUIDtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUIDtfActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NUIDtfActionPerformed

    private void EnablebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnablebtnActionPerformed
        // TODO add your handling code here:
        String NUID = NUIDtf.getText();
        String Username = UserIdtf.getText();
        String role = Roletf.getText();
        String password = String.valueOf(Passwordpf.getPassword());
        boolean Status=false;
        if(!history.getHistory().isEmpty())
        {
            for(Person p:history.getHistory())
            {
            
                if (p.NUID.equals(NUID))
                {
                    Enablebtn.setEnabled(true);
                    Status = true;
         
                    //JOptionPane.showMessageDialog(this,"User enabled");
                }
                //else
                //{
                    //Status = false;
                   // JOptionPane.showMessageDialog(this,"Add the Person details of the user to enable");
                    
               // }
            }
            
            
        }
        /*else
        {
            Status = false;
            JOptionPane.showMessageDialog(this,"Add the Person details of the user to enable");
            //return;
        }*/
        if(Status){
        User user = history1.addUser();
        user.setUsername(Username);
        user.setNUID(NUID);
        user.setRole(role);
        user.setPassword(password);
        user.setStatus(Status);
        JOptionPane.showMessageDialog(this,"User enabled");
        }
        else
        {
             //Status = false;
            JOptionPane.showMessageDialog(this,"Add the Person details of the user to enable");
        
        }
        NUIDtf.setText("");
        UserIdtf.setText("");
        Roletf.setText("");
        Passwordpf.setText("");
        
        
        
    }//GEN-LAST:event_EnablebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enablebtn;
    private javax.swing.JLabel NUIDlbl;
    private javax.swing.JTextField NUIDtf;
    private javax.swing.JLabel Passwordlbl;
    private javax.swing.JPasswordField Passwordpf;
    private javax.swing.JLabel Rolelbl;
    private javax.swing.JTextField Roletf;
    private javax.swing.JLabel Statuslbl;
    private javax.swing.JLabel UserIdlbl;
    private javax.swing.JTextField UserIdtf;
    // End of variables declaration//GEN-END:variables
}
