/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.Password;
import model.Person;
import model.PersonHistory;
import model.User;
import model.UserHistory;


/**
 *
 * @author advai
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    PersonHistory history;
    UserHistory history1;
    Password localPasswordObj;
    public LoginJPanel(PersonHistory history, UserHistory history1) {
        initComponents();
        this.history = history;
        this.history1 = history1;
        
        this.localPasswordObj = new Password("md5");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Useridlbl = new javax.swing.JLabel();
        passlbl = new javax.swing.JLabel();
        Useridtf = new javax.swing.JTextField();
        AdminBtn = new javax.swing.JButton();
        UserBtn = new javax.swing.JButton();
        passpf = new javax.swing.JPasswordField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel1);

        Useridlbl.setText("UserID");

        passlbl.setText("Password");

        AdminBtn.setText("Admin");
        AdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBtnActionPerformed(evt);
            }
        });

        UserBtn.setText("User");
        UserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AdminBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UserBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Useridlbl)
                            .addComponent(passlbl))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Useridtf, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(passpf))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Useridlbl)
                    .addComponent(Useridtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passlbl)
                    .addComponent(passpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminBtn)
                    .addComponent(UserBtn))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBtnActionPerformed
        // TODO add your handling code here:
        
        String UID = Useridtf.getText();
        String PDx = String.valueOf(passpf.getPassword());
        String PD = this.localPasswordObj.hashPassword(PDx);
        if((UID.equals("admin")) && (PDx.equals("123admin"))){
        
        AdminJPanel adminPanel = new AdminJPanel(this.history, this.history1);
        jSplitPane1.setRightComponent(adminPanel);
        LeftJPanel leftPanel = new LeftJPanel();
        jSplitPane1.setLeftComponent(leftPanel);
        
        User user = history1.addUser();
        user.setUsername("Admin");
        user.setNUID("null");
        user.setRole("admin");
        user.setPassword("123admin");
        user.setStatus(true);
        
        /*ExperimentJPanel experimentPanel = new ExperimentJPanel();
        jSplitPane1.setRightComponent(experimentPanel);
        LeftJPanel leftPanel = new LeftJPanel();
        jSplitPane1.setLeftComponent(leftPanel);*/
        
        
        
        //jSplitPanel.setLeftComponent()
        //jSplitPane1.setDividerLocation(2);
        /*AdminJPanel adminPanel = new AdminJPanel();
        jSplitPane1.setLayout(new java.awt.BorderLayout());
        jSplitPane1.removeAll();
        jSplitPane1.add(adminPanel);
        jSplitPane1.revalidate();*/
    }//GEN-LAST:event_AdminBtnActionPerformed
        else{
    JOptionPane.showMessageDialog(this,"Wrong Admin Details");
    }
    }
    private void UserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserBtnActionPerformed
        // TODO add your handling code here:
        boolean found = false;
        String UID = Useridtf.getText();
        String PD = String.valueOf(passpf.getPassword());
        PD = this.localPasswordObj.hashPassword(PD);
        for(User user: history1.getHistory1()){
            if((user.getUsername().equals(UID)) &&(user.getPassword().equals(PD)) && user.Status== true){
              //user.setUsername(user.Username);
              //return user;
              Person pp = this.history.searchPerson(user.getNUID());
              String ID= Useridtf.getText();
                
              
                    
        UserJPanel userPanel = new UserJPanel(this.history, this.history1, pp, user,ID);
        
        
        jSplitPane1.setRightComponent(userPanel);
        LeftJPanel leftPanel = new LeftJPanel();
        jSplitPane1.setLeftComponent(leftPanel);
        
        /*Panel1.setLayout(new java.awt.BorderLayout());
        Panel1.removeAll();
        Panel1.add(userPanel);
        Panel1.revalidate();*/
        found = true;
        break;
        
            }
    }//GEN-LAST:event_UserBtnActionPerformed
         if(!found){
             JOptionPane.showMessageDialog(this,"Wrong User Details");
         }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBtn;
    private javax.swing.JButton UserBtn;
    private javax.swing.JLabel Useridlbl;
    private javax.swing.JTextField Useridtf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel passlbl;
    private javax.swing.JPasswordField passpf;
    // End of variables declaration//GEN-END:variables

}
