/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.User;
import model.UserHistory;

/**
 *
 * @author advai
 */
public class ManageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageJPanel
     */
    public String a;
    public String b;
    public boolean c;
    UserHistory history1;
    User user;
    public ManageJPanel(UserHistory history1) {
        initComponents();
        Disablebtn.setEnabled(false);
        Updatebtn.setEnabled(false);
        Updatepasswordbtn.setEnabled(false);
        updateuseridtf.setEnabled(false);
        updatepasswordtf.setEnabled(false);
        this.history1 = history1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nuidtf = new javax.swing.JTextField();
        Searchbtn = new javax.swing.JButton();
        UserIdlbl = new javax.swing.JLabel();
        Roletf = new javax.swing.JTextField();
        Passwordlbl = new javax.swing.JLabel();
        Statuslbl = new javax.swing.JLabel();
        NUIDtf = new javax.swing.JTextField();
        UserIdtf = new javax.swing.JTextField();
        Passwordpf = new javax.swing.JPasswordField();
        NUIDlbl = new javax.swing.JLabel();
        Rolelbl = new javax.swing.JLabel();
        Statustf = new javax.swing.JTextField();
        Disablebtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();
        Updatepasswordbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        updateuseridtf = new javax.swing.JTextField();
        Updatepasswordlbl = new javax.swing.JLabel();
        updatepasswordtf = new javax.swing.JTextField();

        jLabel1.setText("NUID:");

        Searchbtn.setText("Search");
        Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbtnActionPerformed(evt);
            }
        });

        UserIdlbl.setText("UserId:");

        Roletf.setEditable(false);

        Passwordlbl.setText("Password:");

        Statuslbl.setText("Status:");

        NUIDtf.setEditable(false);
        NUIDtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUIDtfActionPerformed(evt);
            }
        });

        UserIdtf.setEditable(false);

        Passwordpf.setEditable(false);

        NUIDlbl.setText("NUID:");

        Rolelbl.setText("Role:");

        Statustf.setEditable(false);

        Disablebtn.setText("Disabled");
        Disablebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisablebtnActionPerformed(evt);
            }
        });

        Updatebtn.setText("UpdateUserId");
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });

        Updatepasswordbtn.setText("UpdatePassword");
        Updatepasswordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatepasswordbtnActionPerformed(evt);
            }
        });

        jLabel2.setText("NewUserID");

        Updatepasswordlbl.setText("New Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(Searchbtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(nuidtf, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Passwordlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NUIDlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(UserIdlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Rolelbl)
                                    .addComponent(jLabel2)
                                    .addComponent(Statuslbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UserIdtf)
                                    .addComponent(Passwordpf)
                                    .addComponent(Roletf, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(NUIDtf, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(Statustf)
                                    .addComponent(updateuseridtf)
                                    .addComponent(updatepasswordtf)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(Updatepasswordlbl)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Updatepasswordbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Updatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Disablebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nuidtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Disablebtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Searchbtn)
                    .addComponent(Updatebtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Updatepasswordbtn)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NUIDlbl)
                            .addComponent(NUIDtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserIdlbl)
                            .addComponent(UserIdtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Rolelbl)
                            .addComponent(Roletf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Passwordlbl)
                            .addComponent(Passwordpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Statuslbl)
                            .addComponent(Statustf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(updateuseridtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updatepasswordtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Updatepasswordlbl)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NUIDtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUIDtfActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_NUIDtfActionPerformed

    private void SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbtnActionPerformed
        // TODO add your handling code here:
        
        //private String a;
        this.user = history1.searchUser(nuidtf.getText());
        if(this.user != null) {
        
            NUIDtf.setText(this.user.getNUID());
            UserIdtf.setText(this.user.getUsername());
            Roletf.setText(this.user.getRole());
            Passwordpf.setText(this.user.getPassword());
        //a =String.valueOf(this.user.isStatus());
        
            if(this.user.isStatus())
            {
                Statustf.setText("Enabled");  
            }
        
            else
            {
                Statustf.setText("Disabled");
            }
        //User user = history1.addUser();
        /*this.user.setUsername(this.user.getUsername());
        this.user.setNUID(this.user.getNUID());
        this.user.setRole(this.user.getRole());
        this.user.setPassword(this.user.getPassword());
        this.user.setStatus(this.user.isStatus());*/
            Disablebtn.setEnabled(true);
            Updatebtn.setEnabled(true);
            Updatepasswordbtn.setEnabled(true);
            updateuseridtf.setEnabled(true);
            updatepasswordtf.setEnabled(true);
        }
        else
            JOptionPane.showMessageDialog(this, "Enter Valid Nuid");
    }//GEN-LAST:event_SearchbtnActionPerformed

    private void DisablebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisablebtnActionPerformed
        // TODO add your handling code here:
        
         /*history1.deleteUser(user);
         user.setStatus(false);
        user.setNUID("");
        user.setRole("");
        user.setPassword("");
        //user.setStatus("");*/
         
         //User user;
         
         this.c= history1.disableuser(this.user);
         if(this.c==false){
           Statustf.setText("Disabled"); 
           JOptionPane.showMessageDialog(this, "User is disabled");
         }
        //User user = new User(); 
        /*user.setStatus(false);
        if(user.isStatus()== false)
        {
          Statustf.setText("Disabled");  
        }*/
        
         
        
    }//GEN-LAST:event_DisablebtnActionPerformed

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        // TODO add your handling code here:
        
        this.user = history1.updateUserID(updateuseridtf.getText(),nuidtf.getText());
        this.user.setUsername(this.user.getUsername());
        this.user.setNUID(this.user.getNUID());
        this.user.setRole(this.user.getRole());
        //this.user.setPassword(this.user.getPassword());
        this.user.setStatus(this.user.isStatus());
        JOptionPane.showMessageDialog(this, "UserId Updated!");
        
    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void UpdatepasswordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatepasswordbtnActionPerformed
        // TODO add your handling code here:
        this.user = history1.searchUser(nuidtf.getText());
        if(this.user.inOldPasswords(updatepasswordtf.getText()))
            JOptionPane.showMessageDialog(this, "Please do not enter old passwords");
        else {
            this.user.setPassword(String.valueOf(updatepasswordtf.getText()));
            JOptionPane.showMessageDialog(this, "Password Updated");
        }
    }//GEN-LAST:event_UpdatepasswordbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Disablebtn;
    private javax.swing.JLabel NUIDlbl;
    private javax.swing.JTextField NUIDtf;
    private javax.swing.JLabel Passwordlbl;
    private javax.swing.JPasswordField Passwordpf;
    private javax.swing.JLabel Rolelbl;
    private javax.swing.JTextField Roletf;
    private javax.swing.JButton Searchbtn;
    private javax.swing.JLabel Statuslbl;
    private javax.swing.JTextField Statustf;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JButton Updatepasswordbtn;
    private javax.swing.JLabel Updatepasswordlbl;
    private javax.swing.JLabel UserIdlbl;
    private javax.swing.JTextField UserIdtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nuidtf;
    private javax.swing.JTextField updatepasswordtf;
    private javax.swing.JTextField updateuseridtf;
    // End of variables declaration//GEN-END:variables
}
