/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.Person;
import model.PersonHistory;
import model.User;
import model.UserHistory;

/**
 *
 * @author advai
 */
public class UpdateUserIdInUserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateUserIdInUserJPanel
     */
    PersonHistory history;
    UserHistory history1;
    Person person;
    User user;
    String IDD;
    public UpdateUserIdInUserJPanel(Person person, PersonHistory history , UserHistory history1,User user, String IDD) {
        initComponents();
        this.history1=history1;
        this.user = user;
        
        NUIDTF.setText(this.user.getNUID());
        NUIDTF.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NUsIDLbl = new javax.swing.JLabel();
        NUsIDTF = new javax.swing.JTextField();
        UpdateBtn = new javax.swing.JButton();
        NUIDLbl = new javax.swing.JLabel();
        NUIDTF = new javax.swing.JTextField();

        NUsIDLbl.setText("NewUserId:");

        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        NUIDLbl.setText("NUID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NUsIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NUIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NUsIDTF)
                            .addComponent(NUIDTF, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NUIDLbl)
                    .addComponent(NUIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUsIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NUsIDLbl))
                .addGap(53, 53, 53)
                .addComponent(UpdateBtn)
                .addContainerGap(309, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:

        this.user = history1.updateUserID(NUsIDTF.getText(),NUIDTF.getText());
        JOptionPane.showMessageDialog(this, "Username Updated!");
        /* for(User user:History1){
            if(user.Username.equals(IDD))
            {

            }
        }*/
    }//GEN-LAST:event_UpdateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NUIDLbl;
    private javax.swing.JTextField NUIDTF;
    private javax.swing.JLabel NUsIDLbl;
    private javax.swing.JTextField NUsIDTF;
    private javax.swing.JButton UpdateBtn;
    // End of variables declaration//GEN-END:variables
}
