/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import model.Person;
import model.PersonHistory;
import model.User;
import model.UserHistory;

/**
 *
 * @author advai
 */
public class UserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserJPanel
     */
    PersonHistory history;
    UserHistory history1;
    Person pp;
    User user;
    String UID;
    public UserJPanel(PersonHistory personHistory, UserHistory userHistory, Person pp,User user, String UID) {
        initComponents();
        //this.history = new PersonHistory();
        this.history = personHistory;
        this.history1 = userHistory;
        this.pp = pp;
        this.user = user;
        this.UID = UID;
        
        NUIDTf.setText(pp.getNUID());
        NameTf.setText(pp.getName());
        DepartmentTf.setText(pp.getDepartment());
        CgpaTf.setText(String.valueOf(pp.getCgpa()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abc = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        UpdateUIDBtn = new javax.swing.JButton();
        UpdatePassBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        NUIDlbl = new javax.swing.JLabel();
        Namelbl = new javax.swing.JLabel();
        Departmentlbl = new javax.swing.JLabel();
        Cgpalbl = new javax.swing.JLabel();
        NUIDTf = new javax.swing.JTextField();
        NameTf = new javax.swing.JTextField();
        DepartmentTf = new javax.swing.JTextField();
        CgpaTf = new javax.swing.JTextField();

        UpdateUIDBtn.setText("UpdateUserID");
        UpdateUIDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUIDBtnActionPerformed(evt);
            }
        });

        UpdatePassBtn.setText("UpdatePassword");
        UpdatePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePassBtnActionPerformed(evt);
            }
        });

        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UpdatePassBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(UpdateUIDBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LogoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(UpdateUIDBtn)
                .addGap(30, 30, 30)
                .addComponent(UpdatePassBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(LogoutBtn)
                .addGap(101, 101, 101))
        );

        abc.setLeftComponent(jPanel1);

        NUIDlbl.setText("NUID:");

        Namelbl.setText("Name:");

        Departmentlbl.setText("Department:");

        Cgpalbl.setText("Cgpa:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cgpalbl)
                    .addComponent(Departmentlbl)
                    .addComponent(Namelbl)
                    .addComponent(NUIDlbl))
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NUIDTf, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(NameTf)
                    .addComponent(DepartmentTf)
                    .addComponent(CgpaTf))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NUIDlbl)
                    .addComponent(NUIDTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Namelbl)
                    .addComponent(NameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Departmentlbl)
                    .addComponent(DepartmentTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cgpalbl)
                    .addComponent(CgpaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        abc.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abc)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abc)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateUIDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateUIDBtnActionPerformed
        // TODO add your handling code here:
        
        //CreateUserJPanel createPanel = new CreateUserJPanel(this.history1,this.history,this.pp);
        //abc.setRightComponent(createPanel);
        
        //UpdateUserID updateID = new UpdateUserID(this.pp,this.history,this.history1);
        //abc.setRightComponent(updateID);
        UpdateUserIdInUserJPanel U = new UpdateUserIdInUserJPanel(this.pp,this.history,this.history1,this.user,this.UID);
        abc.setRightComponent(U);
        
        
        
    }//GEN-LAST:event_UpdateUIDBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:
        
        
        LoginJPanel loginPanel = new LoginJPanel(this.history,this.history1);
        LeftJPanel leftPanel = new LeftJPanel();
        abc.setRightComponent(loginPanel);
        abc.setLeftComponent(leftPanel);
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void UpdatePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePassBtnActionPerformed
        // TODO add your handling code here:
        UpdatePasswordInUserJPanel U = new UpdatePasswordInUserJPanel(this.pp,this.history,this.history1,this.user,this.UID);
        abc.setRightComponent(U);
    }//GEN-LAST:event_UpdatePassBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CgpaTf;
    private javax.swing.JLabel Cgpalbl;
    private javax.swing.JTextField DepartmentTf;
    private javax.swing.JLabel Departmentlbl;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JTextField NUIDTf;
    private javax.swing.JLabel NUIDlbl;
    private javax.swing.JTextField NameTf;
    private javax.swing.JLabel Namelbl;
    private javax.swing.JButton UpdatePassBtn;
    private javax.swing.JButton UpdateUIDBtn;
    private javax.swing.JSplitPane abc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
